//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDTDD.ServiceReferenceHangSX {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HangSX", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class HangSX : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ten {
            get {
                return this.tenField;
            }
            set {
                if ((object.ReferenceEquals(this.tenField, value) != true)) {
                    this.tenField = value;
                    this.RaisePropertyChanged("ten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceHangSX.IServiceHangSX")]
    public interface IServiceHangSX {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangSX/findAll", ReplyAction="http://tempuri.org/IServiceHangSX/findAllResponse")]
        CuaHangDTDD.ServiceReferenceHangSX.HangSX[] findAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangSX/findAll", ReplyAction="http://tempuri.org/IServiceHangSX/findAllResponse")]
        System.Threading.Tasks.Task<CuaHangDTDD.ServiceReferenceHangSX.HangSX[]> findAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangSX/find", ReplyAction="http://tempuri.org/IServiceHangSX/findResponse")]
        CuaHangDTDD.ServiceReferenceHangSX.HangSX find(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangSX/find", ReplyAction="http://tempuri.org/IServiceHangSX/findResponse")]
        System.Threading.Tasks.Task<CuaHangDTDD.ServiceReferenceHangSX.HangSX> findAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangSX/insert", ReplyAction="http://tempuri.org/IServiceHangSX/insertResponse")]
        bool insert(string ten, bool active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangSX/insert", ReplyAction="http://tempuri.org/IServiceHangSX/insertResponse")]
        System.Threading.Tasks.Task<bool> insertAsync(string ten, bool active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangSX/delete", ReplyAction="http://tempuri.org/IServiceHangSX/deleteResponse")]
        bool delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangSX/delete", ReplyAction="http://tempuri.org/IServiceHangSX/deleteResponse")]
        System.Threading.Tasks.Task<bool> deleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangSX/update", ReplyAction="http://tempuri.org/IServiceHangSX/updateResponse")]
        bool update(int id, string ten, bool active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHangSX/update", ReplyAction="http://tempuri.org/IServiceHangSX/updateResponse")]
        System.Threading.Tasks.Task<bool> updateAsync(int id, string ten, bool active);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceHangSXChannel : CuaHangDTDD.ServiceReferenceHangSX.IServiceHangSX, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHangSXClient : System.ServiceModel.ClientBase<CuaHangDTDD.ServiceReferenceHangSX.IServiceHangSX>, CuaHangDTDD.ServiceReferenceHangSX.IServiceHangSX {
        
        public ServiceHangSXClient() {
        }
        
        public ServiceHangSXClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHangSXClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHangSXClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHangSXClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CuaHangDTDD.ServiceReferenceHangSX.HangSX[] findAll() {
            return base.Channel.findAll();
        }
        
        public System.Threading.Tasks.Task<CuaHangDTDD.ServiceReferenceHangSX.HangSX[]> findAllAsync() {
            return base.Channel.findAllAsync();
        }
        
        public CuaHangDTDD.ServiceReferenceHangSX.HangSX find(int id) {
            return base.Channel.find(id);
        }
        
        public System.Threading.Tasks.Task<CuaHangDTDD.ServiceReferenceHangSX.HangSX> findAsync(int id) {
            return base.Channel.findAsync(id);
        }
        
        public bool insert(string ten, bool active) {
            return base.Channel.insert(ten, active);
        }
        
        public System.Threading.Tasks.Task<bool> insertAsync(string ten, bool active) {
            return base.Channel.insertAsync(ten, active);
        }
        
        public bool delete(int id) {
            return base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
        
        public bool update(int id, string ten, bool active) {
            return base.Channel.update(id, ten, active);
        }
        
        public System.Threading.Tasks.Task<bool> updateAsync(int id, string ten, bool active) {
            return base.Channel.updateAsync(id, ten, active);
        }
  }
}
