//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangDTDD.ServiceReferenceTonKho {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TonKhoe", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class TonKhoe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ngayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> sanpham_chitiet_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soluongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ngay {
            get {
                return this.ngayField;
            }
            set {
                if ((this.ngayField.Equals(value) != true)) {
                    this.ngayField = value;
                    this.RaisePropertyChanged("ngay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> sanpham_chitiet_id {
            get {
                return this.sanpham_chitiet_idField;
            }
            set {
                if ((this.sanpham_chitiet_idField.Equals(value) != true)) {
                    this.sanpham_chitiet_idField = value;
                    this.RaisePropertyChanged("sanpham_chitiet_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soluong {
            get {
                return this.soluongField;
            }
            set {
                if ((this.soluongField.Equals(value) != true)) {
                    this.soluongField = value;
                    this.RaisePropertyChanged("soluong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTonKho.IServiceTonKho")]
    public interface IServiceTonKho {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/findAll", ReplyAction="http://tempuri.org/IServiceTonKho/findAllResponse")]
        CuaHangDTDD.ServiceReferenceTonKho.TonKhoe[] findAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/findAll", ReplyAction="http://tempuri.org/IServiceTonKho/findAllResponse")]
        System.Threading.Tasks.Task<CuaHangDTDD.ServiceReferenceTonKho.TonKhoe[]> findAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/find", ReplyAction="http://tempuri.org/IServiceTonKho/findResponse")]
        CuaHangDTDD.ServiceReferenceTonKho.TonKhoe find(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/find", ReplyAction="http://tempuri.org/IServiceTonKho/findResponse")]
        System.Threading.Tasks.Task<CuaHangDTDD.ServiceReferenceTonKho.TonKhoe> findAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/insert", ReplyAction="http://tempuri.org/IServiceTonKho/insertResponse")]
        bool insert(int soluong, System.DateTime ngay, int sanpham_chitiet_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/insert", ReplyAction="http://tempuri.org/IServiceTonKho/insertResponse")]
        System.Threading.Tasks.Task<bool> insertAsync(int soluong, System.DateTime ngay, int sanpham_chitiet_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/delete", ReplyAction="http://tempuri.org/IServiceTonKho/deleteResponse")]
        bool delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/delete", ReplyAction="http://tempuri.org/IServiceTonKho/deleteResponse")]
        System.Threading.Tasks.Task<bool> deleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/update", ReplyAction="http://tempuri.org/IServiceTonKho/updateResponse")]
        bool update(int id, int soluong, System.DateTime ngay, int sanpham_chitiet_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTonKho/update", ReplyAction="http://tempuri.org/IServiceTonKho/updateResponse")]
        System.Threading.Tasks.Task<bool> updateAsync(int id, int soluong, System.DateTime ngay, int sanpham_chitiet_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTonKhoChannel : CuaHangDTDD.ServiceReferenceTonKho.IServiceTonKho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTonKhoClient : System.ServiceModel.ClientBase<CuaHangDTDD.ServiceReferenceTonKho.IServiceTonKho>, CuaHangDTDD.ServiceReferenceTonKho.IServiceTonKho {
        
        public ServiceTonKhoClient() {
        }
        
        public ServiceTonKhoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTonKhoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTonKhoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTonKhoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CuaHangDTDD.ServiceReferenceTonKho.TonKhoe[] findAll() {
            return base.Channel.findAll();
        }
        
        public System.Threading.Tasks.Task<CuaHangDTDD.ServiceReferenceTonKho.TonKhoe[]> findAllAsync() {
            return base.Channel.findAllAsync();
        }
        
        public CuaHangDTDD.ServiceReferenceTonKho.TonKhoe find(int id) {
            return base.Channel.find(id);
        }
        
        public System.Threading.Tasks.Task<CuaHangDTDD.ServiceReferenceTonKho.TonKhoe> findAsync(int id) {
            return base.Channel.findAsync(id);
        }
        
        public bool insert(int soluong, System.DateTime ngay, int sanpham_chitiet_id) {
            return base.Channel.insert(soluong, ngay, sanpham_chitiet_id);
        }
        
        public System.Threading.Tasks.Task<bool> insertAsync(int soluong, System.DateTime ngay, int sanpham_chitiet_id) {
            return base.Channel.insertAsync(soluong, ngay, sanpham_chitiet_id);
        }
        
        public bool delete(int id) {
            return base.Channel.delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAsync(int id) {
            return base.Channel.deleteAsync(id);
        }
        
        public bool update(int id, int soluong, System.DateTime ngay, int sanpham_chitiet_id) {
            return base.Channel.update(id, soluong, ngay, sanpham_chitiet_id);
        }
        
        public System.Threading.Tasks.Task<bool> updateAsync(int id, int soluong, System.DateTime ngay, int sanpham_chitiet_id) {
            return base.Channel.updateAsync(id, soluong, ngay, sanpham_chitiet_id);
        }
    }
}
